[general]
live_config_reload = true

[window]
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true 
decorations_theme_variant = "None"
decorations = "Full"
opacity = 0.9

[scrolling]
history = 100000
multiplier = 3

[font]
normal = { family = "terminus" }
size = 14
builtin_box_drawing = true 

