#!/usr/bin/env bash
export DOTFILES="$HOME/Dots"
source "$DOTFILES/pretty"

# dconf load / < $DOTS_DIR/gnome-settings

"$DOTFILES/install-packages"

# ./guix-setup --check && sudo ./guix-setup

for src in "$DOTFILES/zsh"/*; do
    execute "ln -sf $src $HOME/.$(basename -- $src)"
done

mkdir -p "$HOME/.local/bin"
for src in "$DOTFILES/scripts"/*; do
    execute "ln -sf $src $HOME/.local/bin/$(basename -- $src)"
done

# symlink the dialog rc file
execute "ln -sf $DOTFILES/dialogrc $HOME/.dialogrc"
