#!/usr/bin/env bash
export DOTFILES=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "$DOTFILES/pretty"

# Replaces DOTFILEs in zshenv to point to 'DOTFILES' here
sed -i 's|DOTFILES=.*$|DOTFILES="'"$DOTFILES"'"|g' "$DOTFILES/zsh/zshenv"

# dconf load / < $DOTS_DIR/gnome-settings

# ./guix-setup --check && sudo ./guix-setup

create_symlinks() {
  for src in "$DOTFILES/zsh"/*; do
      execute "ln -sf $src $HOME/.$(basename -- $src)"
  done

  mkdir -p "$HOME/.local/bin"
  for src in "$DOTFILES/scripts"/*; do
      execute "ln -sf $src $HOME/.local/bin/$(basename -- $src)"
  done

  mkdir -p "$HOME/.config"
  for cfg in "$DOTFILES/config"/*; do
    src="$cfg"
    target="$HOME/.config/$(printf "%s" "$cfg" | sed "s/.*\/\(.*\)/\1/g")"
    execute "ln -sf $src $target" "$src -> $target"
    execute "rm -rf $target/$(basename -- $target)"
  done

  # symlink the dialog rc file
  execute "ln -sf $DOTFILES/dialogrc $HOME/.dialogrc"
}

copy_sway_desktop_session() {
  cp "$DOTFILES/sway.desktop" "/usr/share/wayland-sessions/"
}

[[ -d /usr/share/wayland-sessions/ ]] && copy_sway_desktop_session
[[ "$1" == *i* ]] && "$DOTFILES/scripts/install-packages"
[[ "$1" == *s* ]] && create_symlinks;
