#!/usr/bin/env bash

PACKAGES=(
  "dialog"
  "git"
  "zsh"
  "fzf"
  "neovim"
  "ffmpeg-free"
  "puddletag"
)

sudo dnf update
sudo dnf upgrade
sudo dnf install ${PACKAGES[@]}

# TODO: handle proton mail brige
# https://proton.me/download/bridge/protonmail-bridge-3.13.0-1.x86_64.rpm
