#!/usr/bin/env bash

PACKAGES=(
  "dialog"
  "git"
  "zsh"
  "fzf"
  "neovim"
  "ffmpeg-free"
  "puddletag"
  "tmux"
  "ImageMagick"
  "grim"
  "swayimg"
  "blueman"
  "rofi"
)

sudo dnf update
sudo dnf upgrade
sudo dnf install ${PACKAGES[@]}

# Tmux theme

if [ ! -d "$HOME/.local/share/minimal-tmux-status" ]; then
  mkdir -p "$HOME/.local/share/minimal-tmux-status"
  git clone https://github.com/niksingh710/minimal-tmux-status.git "$HOME/.local/share/minimal-tmux-status"
fi

# Install ocaml

