#!/usr/bin/env bash

COMMON=(
  "dialog"
  "git"
  "zsh"
  "fzf"
  "neovim"
  "ffmpeg-free"
  "puddletag"
  "tmux"
  "ImageMagick"
  "grim"
  "swayimg"
  "blueman"
  "rofi"
  "jq"
  "yad"
  "mako"
)

if command -v dnf >/dev/null
then
  PACKAGES=(
    "${COMMON[@]}"
  )
  sudo dnf update
  sudo dnf upgrade
  sudo dnf install ${PACKAGES[@]}
fi

if command -v pacman >/dev/null
then
  PACKAGES=(
    "${COMMON[@]}"
  )
  sudo pacman -Syu ${PACKAGES[@]}
fi

# Tmux theme

if [ ! -d "$HOME/.local/share/minimal-tmux-status" ]; then
  mkdir -p "$HOME/.local/share/minimal-tmux-status"
  git clone https://github.com/niksingh710/minimal-tmux-status.git "$HOME/.local/share/minimal-tmux-status"
fi

# Install ocaml

## handle mimetypes

xdg-mime default org.pwmt.zathura.desktop application/pdf
