#!/bin/bash

## Alternate https://github.com/D3Ext/aesthetic-wallpapers

REPO_DIR="$HOME/.config/wallpapers"
REPO="https://github.com/makccr/wallpapers"

if [ ! -d "$REPO_DIR/.git" ]; then
  git clone --depth 1 $REPO $REPO_DIR
else
  pushd $REPO_DIR
  git pull -p
  popd
fi

NEW_WALLPAPER=$(sxiv -o -t -r $REPO_DIR/wallpapers/*)

if [[ -n $NEW_WALLPAPER ]]; then
  filename=$(basename -- "$NEW_WALLPAPER")
  extension="${filename##*.}"
  find "$HOME/Desktop" -name 'wallpaper.*' -delete
  cp $NEW_WALLPAPER "$HOME/Desktop/wallpaper.$extension" 
  killall swaybg
  swaybg --image $HOME/Desktop/wallpaper.* & disown
fi
