#!/usr/bin/env bash

COMMON=(
  "dialog"
  "git"
  "zsh"
  "fzf"
  "neovim"
  "ffmpeg-free"
  "puddletag"
  "tmux"
  "ImageMagick"
  "grim"
  "swayimg"
  "blueman"
  "rofi-wayland"
  "jq"
  "yad"
  "mako"
  "vifm"
  "brightnessctl"
  "mpd"
  "ncmpcpp"
  "meson"
  "python3-cogapp"
)

if command -v dnf >/dev/null
then
  PACKAGES=(
    "${COMMON[@]}"
  )
  dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm

  # https://proton.me/download/mail/linux/ProtonMail-desktop-beta.rpm
  # sudo dnf install ProtonMail-desktop-beta.rpm

  dnf update
  dnf upgrade

  dnf install ${PACKAGES[@]}
fi

if command -v pacman >/dev/null
then
  PACKAGES=(
    "${COMMON[@]}"
  )
  pacman -Syu ${PACKAGES[@]}
fi

# Tmux theme

if [ ! -d "$HOME/.local/share/minimal-tmux-status" ]; then
  mkdir -p "$HOME/.local/share/minimal-tmux-status"
  git clone https://github.com/niksingh710/minimal-tmux-status.git "$HOME/.local/share/minimal-tmux-status"
fi

# Install ocaml

## handle mimetypes

xdg-mime default org.pwmt.zathura.desktop application/pdf
