#!/usr/bin/env bash

NOTES_PATH="$HOME/Notes"
DAILY_FOLDER="daily"
DATE_FORMAT="+%Y-%m-%d"
COMMIT_MESSAGE="Note change sync"

mkdir -p "$NOTES_PATH"
mkdir -p "$NOTES_PATH/$DAILY_FOLDER"

new_note() {
  exec 3>&1; # redirect stream 3 to 1
  result=$(dialog \
    --begin 0 0 \
    --inputbox "Enter the name of the new note" \
    8 40 2>&1 1>&3);
  exitcode=$?;
  exec 3>&-;
  echo "$exitcode $result"
  [ "$exitcode" -eq 0 ] && create_new_note "$NOTES_PATH/$result.md" "$result"
}

create_new_note() {
  NAME=${2:-"Header"}
  printf "# $NAME\n\n## Sub heading\n" > "$1"
  $EDITOR "$1"
}

get_daily_note_path() {
  echo "$DAILY_FOLDER/$(date "$DATE_FORMAT").md"
}

open_daily_note() {
  NOTE_PATH="$NOTES_PATH/$(get_daily_note_path)"
  if [ -f "$NOTE_PATH" ]; then
    $EDITOR "$NOTE_PATH" 
  else
    create_new_note "$NOTE_PATH"
  fi
}

open_note() {
  exec 3>&1; # redirect stream 3 to 1
  result=$(dialog \
    --begin 0 0 \
    --title "Choose a note" \
    --fselect $NOTES_PATH/ 14 80 2>&1 1>&3);
  exitcode=$?;
  exec 3>&-;
  [ "$exitcode" -eq 0 ] && $EDITOR "$result"
}

show_command_menu() {
  exec 3>&1; # redirect stream 3 to 1
  result=$(dialog \
    --begin 0 0 \
    --menu 'Choose an action' 18 70 15 \
    "new" "New note" \
    "open" "Open note" \
    "daily" "Open daily note" \
    "status" "Git status for notes" \
    "sync" "Sync notes changes" \
    2>&1 1>&3);
  exitcode=$?;
  exec 3>&-;
  [ "$exitcode" -eq 0 ] && handle_argument "--$result" "return_to_menu"
}

git_status() {
  RETURN="$1"; shift
  # returns git status
  pushd $NOTES_PATH > /dev/null
  STATUS=$(git status)
  popd > /dev/null

  dialog \
    --clear \
    --begin 0 0 \
    --title "Git status" \
    --extra-button "$@" \
    --extra-label "Sync" \
    --msgbox "$STATUS" 22 77;

  [ $? -ne 0 ] && git_sync "$RETURN";
  [ "$RETURN" == "return_to_menu" ] && show_command_menu
}

git_sync() {
  pushd $NOTES_PATH > /dev/null
  git stash > /dev/null
  git pull
  git stash pop
  git add .
  git commit -m "$COMMIT_MESSAGE"
  git push
  popd > /dev/null
  [ "$1" == "return_to_menu" ] && show_command_menu
}

handle_argument() {
  CMD="$1"; shift
  case "$CMD" in
    "--new") new_note $@ ;;
    "--open") open_note $@ ;;
    "--daily") open_daily_note $@ ;;
    "--status") git_status $@ ;;
    # "--sync") git_sync $@ ;;
    *) show_command_menu ;;
  esac
}

handle_argument $1
