#!/usr/bin/env bash

function get-volume {
  pactl list sinks | grep '^[[:space:]]Volume:' | \
    head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,'
}

generate_progress_bar() {
  local percentage=$1
  local total_blocks=20
  local filled_blocks=$((percentage * total_blocks / 100))
  local unfilled_blocks=$((total_blocks - filled_blocks))
  printf '%0.s█' $(seq 1 $filled_blocks)
  printf '%0.s░' $(seq 1 $unfilled_blocks)
}

function notify-volume {
  v=$(get-volume)
  notify-send \
    -e \
    -t 2000 \
    -h string:x-canonical-private-synchronous:audio \
    "Volume" "$(generate_progress_bar "$v") $v%"
}

case "$1" in
  "up") 
    pactl set-sink-volume @DEFAULT_SINK@ "+$2%" 
    notify-volume;;
  "down")
    pactl set-sink-volume @DEFAULT_SINK@ "-$2%" 
    notify-volume;;
  "mute")
    pactl set-sink-mute @DEFAULT_SINK@ toggle ;;
  **)
    echo "Unknown command '$1'"
esac
