export HISTFILE="$ZDOTDIR/.zhistory"    # History filepath
export HISTSIZE=10000                   # Maximum events for internal history
export SAVEHIST=10000                   # Maximum events in history file
export EDITOR="nvim"
export VISUAL="nvim"
export BROWSER="firefox"
export GIT_REVIEW_BASE=main # See gitconfig
export TERM='rxvt-256color'
export REPOS="$HOME/Repos"
# this is platform specific, I should move this to a 
# generated script that isn't versioned controlled 
export DOTFILES="/home/dneumann/.dots"
. "$HOME/.cargo/env"
