export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"

## This isn't that useful since it auto completes arguments :/
ENABLE_CORRECTION="false"

plugins=(git)

source $ZSH/oh-my-zsh.sh

# pnpm
export PNPM_HOME="/home/dneumann/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

export PATH=/home/dneumann/.nimble/bin:$PATH

alias gs="git status"
alias gc="git commit"
alias ga="git add"
alias cls="clear"
