source $HOME/.zalias

PLUGIN_DIR=$HOME/.local/bin/
mkdir -p "$PLUGIN_DIR"

ZSH_AUTO_SUGGESTIONS="$PLUGIN_DIR/zsh-autosuggestions"
ZSH_SYNTAX_HIGHLIGHTING="$PLUGIN_DIR/zsh-syntax-highlighting"
ZSH_BETTER_VI_MODE="$PLUGIN_DIR/zsh-vi-mode"

install_zplugins() {
  if [ ! -f "$ZSH_AUTO_SUGGESTIONS"/zsh-autosuggestions.zsh ]; then
    git clone https://github.com/zsh-users/zsh-autosuggestions $ZSH_AUTO_SUGGESTIONS
  fi
  if [ ! -f "$ZSH_SYNTAX_HIGHLIGHTING"/zsh-syntax-highlighting.zsh ]; then
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_SYNTAX_HIGHLIGHTING
  fi
  if [ ! -f "$ZSH_BETTER_VI_MODE"/zsh-vi-mode.plugin.zsh ]; then
    git clone https://github.com/jeffreytse/zsh-vi-mode.git $ZSH_BETTER_VI_MODE
  fi
}

source_plugins() {
  source "$ZSH_AUTO_SUGGESTIONS/zsh-autosuggestions.zsh"
  source "$ZSH_SYNTAX_HIGHLIGHTING/zsh-syntax-highlighting.zsh"
  source "$ZSH_BETTER_VI_MODE/zsh-vi-mode.plugin.zsh"
}

install_ps1() {
  autoload -U vcs_info
  precmd_vcs_info() { vcs_info }
  precmd_functions+=( precmd_vcs_info )
  setopt prompt_subst
  zstyle ':vcs_info:git:*' formats '%b'

  export PROMPT="%{%F{39}%}%n%{%F{45}%}@%{%F{51}%}%m %{%F{195}%}%~ %{%f%}$ "
  export RPROMPT='${vcs_info_msg_0_}'
}

configure_zsh_navigation() {
  setopt AUTO_CD
  setopt AUTO_PUSHD
  setopt PUSHD_IGNORE_DUPS
  setopt PUSHD_SILENT
  setopt CORRECT # spelling correction
  setopt CDABLE_VARS # can change directory to paths stored in variable
}

configure_zsh_history() {
  setopt EXTENDED_GLOB
  setopt EXTENDED_HISTORY # Write the history file in the ':start:elapsed;command' format.
  setopt SHARE_HISTORY # Share history between all sessions.
  setopt HIST_EXPIRE_DUPS_FIRST # Expire a duplicate event first when trimming history.
  setopt HIST_IGNORE_DUPS # Do not record an event that was just recorded again.
  setopt HIST_IGNORE_ALL_DUPS # Delete an old recorded event if a new event is a duplicate.
  setopt HIST_FIND_NO_DUPS # Do not display a previously found event.
  setopt HIST_IGNORE_SPACE # Do not record an event starting with a space.
  setopt HIST_SAVE_NO_DUPS # Do not write a duplicate event to the history file.
  setopt HIST_VERIFY # Do not execute immediately upon history expansion.
}

configure_zsh() {
  autoload -U compinit; compinit
  configure_zsh_navigation
  configure_zsh_history
}

install_zplugins
source_plugins
install_ps1
configure_zsh
