export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"

## This isn't that useful since it auto completes arguments :/
ENABLE_CORRECTION="false"

# git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
# git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

ZSH_AUTO_SUG_P="${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions"
ZSH_SYNTAX_HL_P="${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions"

if [ -f $ZSH_AUTO_SUG_P ]; then
  git clone https://github.com/zsh-users/zsh-autosuggestions $ZSH_AUTO_SUG_P
fi

if [ -f $ZSH_SYNTAX_HL_P ]; then
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_SYNTAX_HL_P
fi

plugins=(
  zsh-autosuggestions
  zsh-syntax-highlighting
  git
)

bindkey -v
bindkey ^R history-incremental-search-backward 
bindkey ^S history-incremental-search-forward

# Useful keybindings
bindkey -s '^g' 'git status --short^M'

source $ZSH/oh-my-zsh.sh
source "$HOME/.cargo/env"

# pnpm
export PNPM_HOME="/home/dneumann/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end


export PATH=/home/dneumann/.nimble/bin:$PATH
export PATH="$PATH:/home/dneumann/.local/share/JetBrains/Toolbox/scripts"

alias gs="git status"
alias gc="git commit"
alias ga="git add"
alias cls="clear"
alias zellij="zellij -l compact"
alias dots="pushd $HOME/.dots"

export PATH=$PATH:/home/dneumann/.spicetify
export PATH=$PATH:/home/dneumann/.config/scripts
export PATH=$PATH:/home/dneumann/.repos/lem

